// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package info.leochoi;

public final class MarketDataProtos {
  private MarketDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarketDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MarketData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>.google.type.Money bid = 2;</code>
     * @return Whether the bid field is set.
     */
    boolean hasBid();
    /**
     * <code>.google.type.Money bid = 2;</code>
     * @return The bid.
     */
    com.google.type.Money getBid();
    /**
     * <code>.google.type.Money bid = 2;</code>
     */
    com.google.type.MoneyOrBuilder getBidOrBuilder();

    /**
     * <code>.google.type.Money ask = 3;</code>
     * @return Whether the ask field is set.
     */
    boolean hasAsk();
    /**
     * <code>.google.type.Money ask = 3;</code>
     * @return The ask.
     */
    com.google.type.Money getAsk();
    /**
     * <code>.google.type.Money ask = 3;</code>
     */
    com.google.type.MoneyOrBuilder getAskOrBuilder();

    /**
     * <code>.google.type.Money last = 4;</code>
     * @return Whether the last field is set.
     */
    boolean hasLast();
    /**
     * <code>.google.type.Money last = 4;</code>
     * @return The last.
     */
    com.google.type.Money getLast();
    /**
     * <code>.google.type.Money last = 4;</code>
     */
    com.google.type.MoneyOrBuilder getLastOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @return Whether the updateTime field is set.
     */
    boolean hasUpdateTime();
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @return The updateTime.
     */
    com.google.protobuf.Timestamp getUpdateTime();
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.MarketData}
   */
  public static final class MarketData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.MarketData)
      MarketDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarketData.newBuilder() to construct.
    private MarketData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarketData() {
      symbol_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MarketData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MarketData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 18: {
              com.google.type.Money.Builder subBuilder = null;
              if (bid_ != null) {
                subBuilder = bid_.toBuilder();
              }
              bid_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bid_);
                bid_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.type.Money.Builder subBuilder = null;
              if (ask_ != null) {
                subBuilder = ask_.toBuilder();
              }
              ask_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ask_);
                ask_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.type.Money.Builder subBuilder = null;
              if (last_ != null) {
                subBuilder = last_.toBuilder();
              }
              last_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(last_);
                last_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updateTime_ != null) {
                subBuilder = updateTime_.toBuilder();
              }
              updateTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updateTime_);
                updateTime_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.leochoi.MarketDataProtos.internal_static_protobuf_MarketData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.leochoi.MarketDataProtos.internal_static_protobuf_MarketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.leochoi.MarketDataProtos.MarketData.class, info.leochoi.MarketDataProtos.MarketData.Builder.class);
    }

    public static final int SYMBOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BID_FIELD_NUMBER = 2;
    private com.google.type.Money bid_;
    /**
     * <code>.google.type.Money bid = 2;</code>
     * @return Whether the bid field is set.
     */
    @java.lang.Override
    public boolean hasBid() {
      return bid_ != null;
    }
    /**
     * <code>.google.type.Money bid = 2;</code>
     * @return The bid.
     */
    @java.lang.Override
    public com.google.type.Money getBid() {
      return bid_ == null ? com.google.type.Money.getDefaultInstance() : bid_;
    }
    /**
     * <code>.google.type.Money bid = 2;</code>
     */
    @java.lang.Override
    public com.google.type.MoneyOrBuilder getBidOrBuilder() {
      return getBid();
    }

    public static final int ASK_FIELD_NUMBER = 3;
    private com.google.type.Money ask_;
    /**
     * <code>.google.type.Money ask = 3;</code>
     * @return Whether the ask field is set.
     */
    @java.lang.Override
    public boolean hasAsk() {
      return ask_ != null;
    }
    /**
     * <code>.google.type.Money ask = 3;</code>
     * @return The ask.
     */
    @java.lang.Override
    public com.google.type.Money getAsk() {
      return ask_ == null ? com.google.type.Money.getDefaultInstance() : ask_;
    }
    /**
     * <code>.google.type.Money ask = 3;</code>
     */
    @java.lang.Override
    public com.google.type.MoneyOrBuilder getAskOrBuilder() {
      return getAsk();
    }

    public static final int LAST_FIELD_NUMBER = 4;
    private com.google.type.Money last_;
    /**
     * <code>.google.type.Money last = 4;</code>
     * @return Whether the last field is set.
     */
    @java.lang.Override
    public boolean hasLast() {
      return last_ != null;
    }
    /**
     * <code>.google.type.Money last = 4;</code>
     * @return The last.
     */
    @java.lang.Override
    public com.google.type.Money getLast() {
      return last_ == null ? com.google.type.Money.getDefaultInstance() : last_;
    }
    /**
     * <code>.google.type.Money last = 4;</code>
     */
    @java.lang.Override
    public com.google.type.MoneyOrBuilder getLastOrBuilder() {
      return getLast();
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp updateTime_;
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @return Whether the updateTime field is set.
     */
    @java.lang.Override
    public boolean hasUpdateTime() {
      return updateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @return The updateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdateTime() {
      return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      return getUpdateTime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
      }
      if (bid_ != null) {
        output.writeMessage(2, getBid());
      }
      if (ask_ != null) {
        output.writeMessage(3, getAsk());
      }
      if (last_ != null) {
        output.writeMessage(4, getLast());
      }
      if (updateTime_ != null) {
        output.writeMessage(5, getUpdateTime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
      }
      if (bid_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBid());
      }
      if (ask_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAsk());
      }
      if (last_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLast());
      }
      if (updateTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUpdateTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.leochoi.MarketDataProtos.MarketData)) {
        return super.equals(obj);
      }
      info.leochoi.MarketDataProtos.MarketData other = (info.leochoi.MarketDataProtos.MarketData) obj;

      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (hasBid() != other.hasBid()) return false;
      if (hasBid()) {
        if (!getBid()
            .equals(other.getBid())) return false;
      }
      if (hasAsk() != other.hasAsk()) return false;
      if (hasAsk()) {
        if (!getAsk()
            .equals(other.getAsk())) return false;
      }
      if (hasLast() != other.hasLast()) return false;
      if (hasLast()) {
        if (!getLast()
            .equals(other.getLast())) return false;
      }
      if (hasUpdateTime() != other.hasUpdateTime()) return false;
      if (hasUpdateTime()) {
        if (!getUpdateTime()
            .equals(other.getUpdateTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      if (hasBid()) {
        hash = (37 * hash) + BID_FIELD_NUMBER;
        hash = (53 * hash) + getBid().hashCode();
      }
      if (hasAsk()) {
        hash = (37 * hash) + ASK_FIELD_NUMBER;
        hash = (53 * hash) + getAsk().hashCode();
      }
      if (hasLast()) {
        hash = (37 * hash) + LAST_FIELD_NUMBER;
        hash = (53 * hash) + getLast().hashCode();
      }
      if (hasUpdateTime()) {
        hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.leochoi.MarketDataProtos.MarketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.leochoi.MarketDataProtos.MarketData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MarketData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.MarketData)
        info.leochoi.MarketDataProtos.MarketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.leochoi.MarketDataProtos.internal_static_protobuf_MarketData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.leochoi.MarketDataProtos.internal_static_protobuf_MarketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.leochoi.MarketDataProtos.MarketData.class, info.leochoi.MarketDataProtos.MarketData.Builder.class);
      }

      // Construct using info.leochoi.MarketDataProtos.MarketData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        symbol_ = "";

        if (bidBuilder_ == null) {
          bid_ = null;
        } else {
          bid_ = null;
          bidBuilder_ = null;
        }
        if (askBuilder_ == null) {
          ask_ = null;
        } else {
          ask_ = null;
          askBuilder_ = null;
        }
        if (lastBuilder_ == null) {
          last_ = null;
        } else {
          last_ = null;
          lastBuilder_ = null;
        }
        if (updateTimeBuilder_ == null) {
          updateTime_ = null;
        } else {
          updateTime_ = null;
          updateTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.leochoi.MarketDataProtos.internal_static_protobuf_MarketData_descriptor;
      }

      @java.lang.Override
      public info.leochoi.MarketDataProtos.MarketData getDefaultInstanceForType() {
        return info.leochoi.MarketDataProtos.MarketData.getDefaultInstance();
      }

      @java.lang.Override
      public info.leochoi.MarketDataProtos.MarketData build() {
        info.leochoi.MarketDataProtos.MarketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.leochoi.MarketDataProtos.MarketData buildPartial() {
        info.leochoi.MarketDataProtos.MarketData result = new info.leochoi.MarketDataProtos.MarketData(this);
        result.symbol_ = symbol_;
        if (bidBuilder_ == null) {
          result.bid_ = bid_;
        } else {
          result.bid_ = bidBuilder_.build();
        }
        if (askBuilder_ == null) {
          result.ask_ = ask_;
        } else {
          result.ask_ = askBuilder_.build();
        }
        if (lastBuilder_ == null) {
          result.last_ = last_;
        } else {
          result.last_ = lastBuilder_.build();
        }
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.leochoi.MarketDataProtos.MarketData) {
          return mergeFrom((info.leochoi.MarketDataProtos.MarketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.leochoi.MarketDataProtos.MarketData other) {
        if (other == info.leochoi.MarketDataProtos.MarketData.getDefaultInstance()) return this;
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.hasBid()) {
          mergeBid(other.getBid());
        }
        if (other.hasAsk()) {
          mergeAsk(other.getAsk());
        }
        if (other.hasLast()) {
          mergeLast(other.getLast());
        }
        if (other.hasUpdateTime()) {
          mergeUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.leochoi.MarketDataProtos.MarketData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.leochoi.MarketDataProtos.MarketData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 1;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 1;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 1;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private com.google.type.Money bid_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> bidBuilder_;
      /**
       * <code>.google.type.Money bid = 2;</code>
       * @return Whether the bid field is set.
       */
      public boolean hasBid() {
        return bidBuilder_ != null || bid_ != null;
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       * @return The bid.
       */
      public com.google.type.Money getBid() {
        if (bidBuilder_ == null) {
          return bid_ == null ? com.google.type.Money.getDefaultInstance() : bid_;
        } else {
          return bidBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public Builder setBid(com.google.type.Money value) {
        if (bidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bid_ = value;
          onChanged();
        } else {
          bidBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public Builder setBid(
          com.google.type.Money.Builder builderForValue) {
        if (bidBuilder_ == null) {
          bid_ = builderForValue.build();
          onChanged();
        } else {
          bidBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public Builder mergeBid(com.google.type.Money value) {
        if (bidBuilder_ == null) {
          if (bid_ != null) {
            bid_ =
              com.google.type.Money.newBuilder(bid_).mergeFrom(value).buildPartial();
          } else {
            bid_ = value;
          }
          onChanged();
        } else {
          bidBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public Builder clearBid() {
        if (bidBuilder_ == null) {
          bid_ = null;
          onChanged();
        } else {
          bid_ = null;
          bidBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public com.google.type.Money.Builder getBidBuilder() {
        
        onChanged();
        return getBidFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      public com.google.type.MoneyOrBuilder getBidOrBuilder() {
        if (bidBuilder_ != null) {
          return bidBuilder_.getMessageOrBuilder();
        } else {
          return bid_ == null ?
              com.google.type.Money.getDefaultInstance() : bid_;
        }
      }
      /**
       * <code>.google.type.Money bid = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
          getBidFieldBuilder() {
        if (bidBuilder_ == null) {
          bidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                  getBid(),
                  getParentForChildren(),
                  isClean());
          bid_ = null;
        }
        return bidBuilder_;
      }

      private com.google.type.Money ask_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> askBuilder_;
      /**
       * <code>.google.type.Money ask = 3;</code>
       * @return Whether the ask field is set.
       */
      public boolean hasAsk() {
        return askBuilder_ != null || ask_ != null;
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       * @return The ask.
       */
      public com.google.type.Money getAsk() {
        if (askBuilder_ == null) {
          return ask_ == null ? com.google.type.Money.getDefaultInstance() : ask_;
        } else {
          return askBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public Builder setAsk(com.google.type.Money value) {
        if (askBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ask_ = value;
          onChanged();
        } else {
          askBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public Builder setAsk(
          com.google.type.Money.Builder builderForValue) {
        if (askBuilder_ == null) {
          ask_ = builderForValue.build();
          onChanged();
        } else {
          askBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public Builder mergeAsk(com.google.type.Money value) {
        if (askBuilder_ == null) {
          if (ask_ != null) {
            ask_ =
              com.google.type.Money.newBuilder(ask_).mergeFrom(value).buildPartial();
          } else {
            ask_ = value;
          }
          onChanged();
        } else {
          askBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public Builder clearAsk() {
        if (askBuilder_ == null) {
          ask_ = null;
          onChanged();
        } else {
          ask_ = null;
          askBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public com.google.type.Money.Builder getAskBuilder() {
        
        onChanged();
        return getAskFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      public com.google.type.MoneyOrBuilder getAskOrBuilder() {
        if (askBuilder_ != null) {
          return askBuilder_.getMessageOrBuilder();
        } else {
          return ask_ == null ?
              com.google.type.Money.getDefaultInstance() : ask_;
        }
      }
      /**
       * <code>.google.type.Money ask = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
          getAskFieldBuilder() {
        if (askBuilder_ == null) {
          askBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                  getAsk(),
                  getParentForChildren(),
                  isClean());
          ask_ = null;
        }
        return askBuilder_;
      }

      private com.google.type.Money last_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> lastBuilder_;
      /**
       * <code>.google.type.Money last = 4;</code>
       * @return Whether the last field is set.
       */
      public boolean hasLast() {
        return lastBuilder_ != null || last_ != null;
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       * @return The last.
       */
      public com.google.type.Money getLast() {
        if (lastBuilder_ == null) {
          return last_ == null ? com.google.type.Money.getDefaultInstance() : last_;
        } else {
          return lastBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public Builder setLast(com.google.type.Money value) {
        if (lastBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          last_ = value;
          onChanged();
        } else {
          lastBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public Builder setLast(
          com.google.type.Money.Builder builderForValue) {
        if (lastBuilder_ == null) {
          last_ = builderForValue.build();
          onChanged();
        } else {
          lastBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public Builder mergeLast(com.google.type.Money value) {
        if (lastBuilder_ == null) {
          if (last_ != null) {
            last_ =
              com.google.type.Money.newBuilder(last_).mergeFrom(value).buildPartial();
          } else {
            last_ = value;
          }
          onChanged();
        } else {
          lastBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public Builder clearLast() {
        if (lastBuilder_ == null) {
          last_ = null;
          onChanged();
        } else {
          last_ = null;
          lastBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public com.google.type.Money.Builder getLastBuilder() {
        
        onChanged();
        return getLastFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      public com.google.type.MoneyOrBuilder getLastOrBuilder() {
        if (lastBuilder_ != null) {
          return lastBuilder_.getMessageOrBuilder();
        } else {
          return last_ == null ?
              com.google.type.Money.getDefaultInstance() : last_;
        }
      }
      /**
       * <code>.google.type.Money last = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
          getLastFieldBuilder() {
        if (lastBuilder_ == null) {
          lastBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                  getLast(),
                  getParentForChildren(),
                  isClean());
          last_ = null;
        }
        return lastBuilder_;
      }

      private com.google.protobuf.Timestamp updateTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       * @return Whether the updateTime field is set.
       */
      public boolean hasUpdateTime() {
        return updateTimeBuilder_ != null || updateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       * @return The updateTime.
       */
      public com.google.protobuf.Timestamp getUpdateTime() {
        if (updateTimeBuilder_ == null) {
          return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        } else {
          return updateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateTime_ = value;
          onChanged();
        } else {
          updateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder setUpdateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updateTimeBuilder_ == null) {
          updateTime_ = builderForValue.build();
          onChanged();
        } else {
          updateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (updateTime_ != null) {
            updateTime_ =
              com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
          } else {
            updateTime_ = value;
          }
          onChanged();
        } else {
          updateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder clearUpdateTime() {
        if (updateTimeBuilder_ == null) {
          updateTime_ = null;
          onChanged();
        } else {
          updateTime_ = null;
          updateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
        
        onChanged();
        return getUpdateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
        if (updateTimeBuilder_ != null) {
          return updateTimeBuilder_.getMessageOrBuilder();
        } else {
          return updateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdateTimeFieldBuilder() {
        if (updateTimeBuilder_ == null) {
          updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdateTime(),
                  getParentForChildren(),
                  isClean());
          updateTime_ = null;
        }
        return updateTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.MarketData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.MarketData)
    private static final info.leochoi.MarketDataProtos.MarketData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.leochoi.MarketDataProtos.MarketData();
    }

    public static info.leochoi.MarketDataProtos.MarketData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarketData>
        PARSER = new com.google.protobuf.AbstractParser<MarketData>() {
      @java.lang.Override
      public MarketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarketData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MarketData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarketData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.leochoi.MarketDataProtos.MarketData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MarketData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_MarketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021market_data.proto\022\010protobuf\032\037google/pr" +
      "otobuf/timestamp.proto\032)api-common-proto" +
      "s/google/type/money.proto\"\261\001\n\nMarketData" +
      "\022\016\n\006symbol\030\001 \001(\t\022\037\n\003bid\030\002 \001(\0132\022.google.t" +
      "ype.Money\022\037\n\003ask\030\003 \001(\0132\022.google.type.Mon" +
      "ey\022 \n\004last\030\004 \001(\0132\022.google.type.Money\022/\n\013" +
      "update_time\030\005 \001(\0132\032.google.protobuf.Time" +
      "stampB \n\014info.leochoiB\020MarketDataProtosb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.MoneyProto.getDescriptor(),
        });
    internal_static_protobuf_MarketData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_MarketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_MarketData_descriptor,
        new java.lang.String[] { "Symbol", "Bid", "Ask", "Last", "UpdateTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.MoneyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
